# Generated by Django 3.2.6 on 2023-06-29 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('created_at', 'title'), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(help_text='Расскажите о товаре', max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Назначьте цену', null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Введите название товара', max_length=200, null=True, verbose_name='Название'),
        ),
    ]
