# Generated by Django 3.2.6 on 2023-07-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Разместите фото для объявления', null=True, upload_to='ad_images/', verbose_name='Фото'),
        ),
    ]
